[package]
name = "valida-basic"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "valida"
path = "src/bin/valida.rs"

[dependencies]
valida-alu-u32 = { path = "../alu_u32" }
valida-bus = { path = "../bus" }
valida-cpu = { path = "../cpu" }
valida-derive = { path = "../derive" }
valida-machine = { path = "../machine" }
valida-memory = { path = "../memory" }
valida-output = { path = "../output" }
valida-program = { path = "../program" }
valida-range = { path = "../range" }
p3-maybe-rayon = { path = "../../Plonky3/maybe-rayon" }
p3-baby-bear = { path = "../../Plonky3/baby-bear" }
byteorder = "1.4.3"
clap = { version = "4.3.19", features = ["derive"] }
tracing = "0.1.37"

[dev-dependencies]
p3-challenger = { path = "../../Plonky3/challenger" }
p3-dft = { path = "../../Plonky3/dft" }
p3-field = { path = "../../Plonky3/field" }
p3-fri = { path = "../../Plonky3/fri" }
p3-keccak = { path = "../../Plonky3/keccak" }
p3-ldt = { path = "../../Plonky3/ldt" }
p3-mds = { path = "../../Plonky3/mds" }
p3-merkle-tree = { path = "../../Plonky3/merkle-tree" }
p3-poseidon = { path = "../../Plonky3/poseidon" }
p3-symmetric = { path = "../../Plonky3/symmetric" }
rand = "0.8.5"
