[package]
name = "valida-basic"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
valida-alu-u32 = { path = "../alu_u32" }
valida-bus = { path = "../bus" }
valida-cpu = { path = "../cpu" }
valida-derive = { path = "../derive" }
valida-machine = { path = "../machine" }
valida-memory = { path = "../memory" }
valida-range = { path = "../range" }
p3-maybe-rayon = { path = "../../Plonky3/maybe-rayon" }

[dev-dependencies]
p3-brakedown = { path = "../../Plonky3/brakedown" }
p3-challenger = { path = "../../Plonky3/challenger" }
p3-field = { path = "../../Plonky3/field" }
p3-merkle-tree = { path = "../../Plonky3/merkle-tree" }
p3-mersenne-31 = { path = "../../Plonky3/mersenne-31" }
p3-poseidon = { path = "../../Plonky3/poseidon" }
p3-symmetric = { path = "../../Plonky3/symmetric" }
p3-tensor-pcs = { path = "../../Plonky3/tensor-pcs" }
rand = "0.8.5"
